FROM ubuntu:16.04

ARG DOCKER_TAG

ENV ENV_NAME=ai4foodsecurity

# the base image does not have wget
RUN apt-get update
RUN apt-get install -y wget

SHELL [ "/bin/bash", "--login", "-c" ]

# install miniconda (using fixed version)
# Mistral GPUs -- Python 3.7 worked
ENV CONDA_DIR $HOME/miniconda3
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py37_4.9.2-Linux-x86_64.sh -O ~/miniconda.sh  && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p $CONDA_DIR  && \
    rm ~/miniconda.sh

# make non-activate conda commands available
ENV PATH=$CONDA_DIR/bin:$PATH

# make conda activate command available from /bin/bash --login shells
RUN echo ". $CONDA_DIR/etc/profile.d/conda.sh" >> ~/.profile

# make conda activate command available from /bin/bash --interative shells
RUN source ~/.bashrc
RUN conda init bash

# install directly in conda base
RUN conda install pandas geopandas rasterio matplotlib numpy sh ipykernel && \
    pip install eo-learn breizhcrops sentinelhub radiant-mlhub && \
    conda clean --all --yes
