FROM centos:centos8.4.2105

ARG DOCKER_TAG

ENV ENV_NAME=ai4food

# the centos base image does not have wget
RUN yum search wget
RUN yum -y install wget

# Following the description here:
# https://towardsdatascience.com/conda-pip-and-docker-ftw-d64fe638dc45

SHELL [ "/bin/bash", "--login", "-c" ]

# Create a non-root user
# NOTE: This is done for docker security purposes
#	ARG username=useless-user
#	ARG uid=1000
#	ARG gid=100
#	ENV USER $username
#	ENV UID $uid
#	ENV GID $gid
#	ENV HOME /home/$USERRUN adduser --disabled-password \
#	    --gecos "Non-root user" \
#	    --uid $UID \
#	    --gid $GID \
#	    --home $HOME \
#	    $USER

# The kernel environment needs to be copied as root
# Assumes the docker build context as the git project root directory
COPY ./docker/kernel-env-cuda11.yaml /tmp/
#	RUN chown $UID:$GID /tmp/kernel-env-cuda11.yaml 

COPY ./docker/entrypoint.sh /usr/local/bin/
#	RUN chown $UID:$GID /usr/local/bin/entrypoint.sh && \
#    chmod u+x /usr/local/bin/entrypoint.sh

#USER $USER

# install miniconda (using fixed version)
ENV MINICONDA_VERSION 4.10.3
ENV CONDA_DIR $HOME/miniconda3
#RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-$MINICONDA_VERSION-Linux-x86_64.sh -O ~/miniconda.sh  
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh -O ~/miniconda.sh  && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p $CONDA_DIR  && \
    rm ~/miniconda.sh

# make non-activate conda commands available
ENV PATH=$CONDA_DIR/bin:$PATH

# make conda activate command available from /bin/bash --login shells
RUN echo ". $CONDA_DIR/etc/profile.d/conda.sh" >> ~/.profile

# make conda activate command available from /bin/bash --interative shells
RUN source ~/.bashrc
RUN conda init bash

# create a project directory inside user home
ENV PROJECT_DIR $HOME/app
RUN mkdir $PROJECT_DIR
WORKDIR $PROJECT_DIR

# build the conda environment
ENV ENV_PREFIX $PWD/env
RUN conda update --name base --channel defaults conda && \
    conda env create --prefix $ENV_PREFIX --file /tmp/kernel-env-cuda11.yaml --force && \
    conda clean --all --yes

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

# # default command will launch JupyterLab server for development
# CMD [ "jupyter", "lab", "--no-browser", "--ip", "0.0.0.0" ]
